# Generated by Django 5.1.6 on 2025-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "initial_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("purchase_date", models.DateField()),
                ("investment_type", models.CharField(max_length=50)),
            ],
        ),
    ]
