# Generated by Django 5.1.6 on 2025-03-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Ahorro', 'Ahorro'), ('Inversión a Largo Plazo', 'Inversión a Largo Plazo'), ('Gastos Médicos', 'Gastos Médicos'), ('Educación', 'Educación'), ('Viajes', 'Viajes'), ('Emergencias', 'Emergencias')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='purposes',
            field=models.ManyToManyField(related_name='transactions', to='transactions.purpose'),
        ),
    ]
